### ISSUE TITLE
Jib Core has been released

### ISSUE THREAD

**Issue by coollog** [schmitch/sbt-jib#11]
Hi @schmitch , we have released the first alpha version of Jib Core (`v0.1.0`) and would like to invite you to try using it in the plugin! Let us know if you have any questions/issues/feedback! The initial documentation is at https://github.com/GoogleContainerTools/jib/tree/master/jib-core but you can also reference the Maven/Gradle plugins for how they currently use the Jib Core API.

**Comment by schmitch** [comment]
Thanks for the info!
I will try it out as soon as I got some time

**Comment by schmitch** [comment]
Fixed in #13
