### ISSUE TITLE
Contribute to sbt-native-packager

### ISSUE THREAD

**Issue by cricket007** [schmitch/sbt-jib#17]
https://github.com/sbt/sbt-native-packager

AFAICT, this is their source code. 
https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/docker/DockerPlugin.scala

**Comment by schmitch** [comment]
Actually the scope of this project, is just to Act as a sbt plugin for jib, i actually use the apache 2 license so i habe no problem in somebody Takes my work and uses it inside sbt-native-packager
