### ISSUE TITLE
make it possible to create releases via Travis CI

### ISSUE THREAD

**Issue by schmitch** [schmitch/sbt-jib#25]
currently releases are done via my local computer, however it would be great to have the same system as quill, which can create releases via PR.

**Comment by sullis** [comment]
This project no longer uses Travis CI.   We should figure out how to enable releases with the GitHub Action Workflow.

**Comment by schmitch** [comment]
yeah it would be great if that would be possible, sadly I'm not really that familiar with github action workflows.

**Comment by sideeffffect** [comment]
[`sbt-ci-release`](https://github.com/olafurpg/sbt-ci-release) is a great plugin for painless publishing to Maven Cenral

https://github.com/olafurpg/setup-scala is a set-up for GitHub actions
